#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Flush DNS
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🌐

# Documentation:
# @raycast.description Flush the local DNS cache and restart mDNSResponder
# @raycast.author johnsyweb
# @raycast.authorURL https://raycast.com/johnsyweb

dscacheutil -flushcache
sudo killall -HUP mDNSResponder
echo "DNS cache flushed"
