#!/usr/bin/env ruby
# frozen_string_literal: true

FZF = "fzf --height 40% --border --reverse --preview 'git log --color=always {} -10'"
BRANCHES = `git branch --all`.freeze

candidates = []

BRANCHES.split("\n").each do |line|
  name = line.split(" ").last
  if name.start_with?("remotes/")
    remote_branch = name.delete_prefix("remotes/")
    candidates << remote_branch unless candidates.include?(remote_branch)
    local_branch = remote_branch.sub(%r{[^/]+/}, "")
    candidates << local_branch unless candidates.include?(local_branch)
  else
    candidates << name unless candidates.include?(name)
  end
end

IO.popen(FZF, "r+") do |fzf|
  fzf.write("#{candidates.join("\n")}\n")
  branch = fzf.read.strip

  `git checkout "#{branch}"` unless branch.empty?
end
