#!/bin/bash
set -e

# Expands short URLS

USAGE="Usage: $0 url1 url2 url3 ... urlN"

if [ "$#" == "0" ]; then
    echo "${USAGE}"
    exit 1
fi

while (( "$#" )); do
    url=$1
    echo -n "${url} ⇒ "
    curl -sL -w "[%{http_code}] %{url_effective}\\n" "${url}" -o /dev/null
    shift
done


