#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Expand Short URL
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🔗
# @raycast.argument1 { "type": "text", "placeholder": "short URL" }

# Documentation:
# @raycast.description Expand a short URL and show the final destination
# @raycast.author johnsyweb
# @raycast.authorURL https://raycast.com/johnsyweb

set -e

# Expands short URLS

USAGE="Usage: $0 url1 url2 url3 ... urlN"

if [ "$#" == "0" ]; then
    echo "${USAGE}"
    exit 1
fi

while (( "$#" )); do
    url=$1
    echo -n "${url} ⇒ "
    curl -sL -w "[%{http_code}] %{url_effective}\\n" "${url}" -o /dev/null
    shift
done
