#!/usr/bin/env zsh

set +e
set +x

git stash
git checkout master
git fetch --all --prune
BRANCH_NAME="upstream-changes-$(date +"%Y%m%d")"
git branch -D ${BRANCH_NAME}
git checkout -b ${BRANCH_NAME}
git reset --hard upstream/master
git smart-merge origin/master

