#!/usr/bin/env zsh

for d in ~/src/*/.git; do
    pushd "${d:h}"
    pwd
    if [[ 0 -eq $(git remote -v | egrep -c 'github\.com[:/]envato/') ]]; then
        echo 'Personal repository'
        git config --local user.email paj+github@johnsy.com
        git config --local user.signingkey F05BBF16907F7671
    else
        echo 'Work repository'
        git config --local user.email pete.johns@envato.com
        git config --local user.signingkey DF64578A90E4F4B0
    fi
    popd
done
