#!/usr/bin/env bash

set -e -u -o pipefail

if [ $# -eq 0 ]; then
  echo "Usage: $0 <domain>"
  exit 1
fi
export DOMAIN=$1

echo | openssl s_client -showcerts -servername "${DOMAIN}" -connect "${DOMAIN}:443" 2>|/dev/null | openssl x509 -inform pem -noout -text | awk -F':' '$1 ~ /^[[:space:]]*Subject$/ { print $2 }'
