#!/usr/bin/env bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Show SSL Subject
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🔒
# @raycast.argument1 { "type": "text", "placeholder": "domain" }

# Documentation:
# @raycast.description Show the TLS certificate subject for a domain
# @raycast.author johnsyweb
# @raycast.authorURL https://raycast.com/johnsyweb

set -e -u -o pipefail

if [ $# -eq 0 ]; then
  echo "Usage: $0 <domain>"
  exit 1
fi
export DOMAIN=$1

echo -e "HEAD / HTTP/1.1\r\nHost: ${DOMAIN}\r\n\r\n" | openssl s_client -quiet -connect ${DOMAIN}:443

echo | openssl s_client -showcerts -servername "${DOMAIN}" -connect "${DOMAIN}:443" 2>|/dev/null | openssl x509 -inform pem -noout -text | awk -F':' '$1 ~ /^[[:space:]]*Subject$/ { print $2 }'
