#!/bin/bash

# Update for the current ruby
ruby --version && gem update --system && gem --version

# Update for all the versions installed via rbenv
for ruby in $(rbenv versions | awk '$1 ~ /[0-9]/ { print $1 }'); do
  export RBENV_VERSION=${ruby}
  ruby --version && gem update --system && gem --version
done

# Update system ruby using sudo...
export RBENV_VERSION=system
ruby --version && sudo gem update --system && gem --version
