#!/usr/bin/env bash

set -euo pipefail

"${HOME}/bin/fetch-all-repos"
brew doctor && brew update && brew upgrade && brew cleanup && brew bundle dump --describe --force --file="${HOME}/.Brewfile"

echo "All done!"
